version: '3'

services:
  jenkins:
    image: jenkins_docker:latest
    restart: always  
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - '$PWD/jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'

  nexus:
    image: dockette/nexus:latest
    ports:
      - '8081:8081'
    volumes:
      - '$PWD/Nexus_data:/nexus-data'

  sonarqube:
    image: sonarqube:latest
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - '9000:9000'
    volumes:
      - '$PWD/Sonarqube_data/data:/opt/sonarqube/data'
      - '$PWD/Sonarqube_data/logs:/opt/sonarqube/logs'
      - '$PWD/Sonarqube_data/extensions:/opt/sonarqube/extensions'
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
volumes:
  postgresql:
  postgresql_data:
