---
apiVersion: v1
kind: Service
metadata:
  name: portal-devops-svc
  namespace: nm-devops
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    run: portal-devops
  type: ClusterIP